### ISSUE TITLE
Editor for Stash 1.4.2 is not compatible with any Stash version below 3.10

### ISSUE THREAD

**Issue by gabriellezbautista** [mohamicorp/editor-for-stash-issues#14]
Attached is our Stash logs. It's seems that it is waiting for another plugin. 
(atlassian-stash.201507014.gb280s.log)

I tried to disable the Badgr plugin which is flooding the logs with errors and there's another error in the logs 
(atlassian-stash.201507014.without_badgr.log)

<code>
2015-07-14 16:33:52,609 WARN  [http-nio-7990-exec-8] gb280s @D3TJV1x993x169x0 ifidi8 170.252.51.2,127.0.0.1 "PUT /rest/plugins/1.0/com.mohamicorp.stash.plugin.editor-for-stash-key HTTP/1.1" c.a.plugin.impl.AbstractPlugin Unable to enable plugin 'com.mohamicorp.stash.plugin.editor-for-stash'
2015-07-14 16:33:52,639 WARN  [http-nio-7990-exec-8] gb280s @D3TJV1x993x169x0 ifidi8 170.252.51.2,127.0.0.1 "PUT /rest/plugins/1.0/com.mohamicorp.stash.plugin.editor-for-stash-key HTTP/1.1" c.a.plugin.impl.AbstractPlugin Because of this exception
com.atlassian.plugin.osgi.container.OsgiContainerException: Cannot start plugin: com.mohamicorp.stash.plugin.editor-for-stash
        at com.atlassian.plugin.osgi.factory.OsgiPlugin.enableInternal(OsgiPlugin.java:484) ~[atlassian-plugins-osgi-3.2.19.jar:na]
        at com.atlassian.plugin.impl.AbstractPlugin.enable(AbstractPlugin.java:310) ~[atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:136) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:104) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.enableAllRecursively(PluginEnabler.java:71) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.DefaultPluginManager.enablePlugins(DefaultPluginManager.java:1813) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.stash.internal.plugin.ClusteredPluginController.enablePlugins(ClusteredPluginController.java:54) [stash-platform-3.9.1.jar:na]
        at sun.proxy.$Proxy293.enablePlugins(Unknown Source) [na:na]
        at sun.proxy.$Proxy1338.enablePlugins(Unknown Source) [na:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:84) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:60) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:25) [sal-core-2.13.4.jar:na]
        at com.atlassian.stash.internal.sal.spi.HostContextAccessorImpl.doInTransaction(HostContextAccessorImpl.java:27) [stash-platform-3.9.1.jar:na]
        at sun.proxy.$Proxy244.doInTransaction(Unknown Source) [na:na]
        at sun.proxy.$Proxy272.doInTransaction(Unknown Source) [na:na]
        at sun.proxy.$Proxy520.doInTransaction(Unknown Source) [na:na]
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:21) [sal-core-2.13.4.jar:na]
        at sun.proxy.$Proxy1337.execute(Unknown Source) [na:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl.enablePlugin(PluginEnablementServiceImpl.java:59) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.upm.core.rest.resources.PluginResource.put(PluginResource.java:131) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1427884372000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) [atlassian-trusted-apps-core-4.0.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1427884374000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.65.1_1428725768000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.65.1_1428725768000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:82) [stash-service-impl-3.9.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_13]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_13]
        ... 282 frames trimmed
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle com.mohamicorp.stash.plugin.editor-for-stash [111]: Unable to resolve 111.0: missing requirement [111.0] package; (package=com.atlassian.stash.repository.ref.restriction)
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3564) ~[org.apache.felix.framework-3.2.2.jar:na]
        ... 34 common frames omitted
2015-07-14 16:33:52,656 ERROR [http-nio-7990-exec-8] gb280s @D3TJV1x993x169x0 ifidi8 170.252.51.2,127.0.0.1 "PUT /rest/plugins/1.0/com.mohamicorp.stash.plugin.editor-for-stash-key HTTP/1.1" c.a.plugin.manager.PluginEnabler Unable to enable plugin com.mohamicorp.stash.plugin.editor-for-stash
com.atlassian.plugin.osgi.container.OsgiContainerException: Cannot start plugin: com.mohamicorp.stash.plugin.editor-for-stash
        at com.atlassian.plugin.osgi.factory.OsgiPlugin.enableInternal(OsgiPlugin.java:484) ~[atlassian-plugins-osgi-3.2.19.jar:na]
        at com.atlassian.plugin.impl.AbstractPlugin.enable(AbstractPlugin.java:310) ~[atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:136) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:104) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.PluginEnabler.enableAllRecursively(PluginEnabler.java:71) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.plugin.manager.DefaultPluginManager.enablePlugins(DefaultPluginManager.java:1813) [atlassian-plugins-core-3.2.19.jar:na]
        at com.atlassian.stash.internal.plugin.ClusteredPluginController.enablePlugins(ClusteredPluginController.java:54) [stash-platform-3.9.1.jar:na]
        at sun.proxy.$Proxy293.enablePlugins(Unknown Source) [na:na]
        at sun.proxy.$Proxy1338.enablePlugins(Unknown Source) [na:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:84) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:60) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:25) [sal-core-2.13.4.jar:na]
        at com.atlassian.stash.internal.sal.spi.HostContextAccessorImpl.doInTransaction(HostContextAccessorImpl.java:27) [stash-platform-3.9.1.jar:na]
        at sun.proxy.$Proxy244.doInTransaction(Unknown Source) [na:na]
        at sun.proxy.$Proxy272.doInTransaction(Unknown Source) [na:na]
        at sun.proxy.$Proxy520.doInTransaction(Unknown Source) [na:na]
        at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:21) [sal-core-2.13.4.jar:na]
        at sun.proxy.$Proxy1337.execute(Unknown Source) [na:na]
        at com.atlassian.upm.core.impl.PluginEnablementServiceImpl.enablePlugin(PluginEnablementServiceImpl.java:59) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.upm.core.rest.resources.PluginResource.put(PluginResource.java:131) [plugin.7609327746158691916.atlassian-universal-plugin-manager-plugin-2.18.5_1433430154000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1427884372000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) [atlassian-trusted-apps-core-4.0.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1427884374000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.65.1_1428725768000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.65.1_1428725768000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:82) [stash-service-impl-3.9.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_13]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_13]
        ... 282 frames trimmed
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle com.mohamicorp.stash.plugin.editor-for-stash [111]: Unable to resolve 111.0: missing requirement [111.0] package; (package=com.atlassian.stash.repository.ref.restriction)
        at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3564) ~[org.apache.felix.framework-3.2.2.jar:na]
        ... 34 common frames omitted
2015-07-14 16:33:52,703 INFO  [http-nio-7990-exec-8] gb280s @D3TJV1x993x169x0 ifidi8 170.252.51.2,127.0.0.1 "PUT /rest/plugins/1.0/com.mohamicorp.stash.plugin.editor-for-stash-key HTTP/1.1" c.a.u.c.l.PluginSettingsAuditLogService Tue Jul 14 16:33:52 CDT 2015 51: Failed to enable add-on Editor for Stash (com.mohamicorp.stash.plugin.editor-for-stash)
</code>

**Comment by mdavoodi** [comment]
It looks like the permission service change in Stash 3.10 is not backwards compatible with the older stash versions. You will either have to update Stash, or use version 1.4.1 of the Editor. We will maintain compatibility and continue feature development for both until we can find a clean way to resolve the issue.

**Comment by gabriellezbautista** [comment]
Thanks for the prompt reply, I updated our plugin and it seems to be working now.

**Comment by javaerb** [comment]
should this be closed?

**Comment by gabriellezbautista** [comment]
Yes, I forgot to close it. Apologies.
