### ISSUE TITLE
Edit -> commit (back to branch) gives a 500 error

### ISSUE THREAD

**Issue by gadg3ts** [mohamicorp/editor-for-stash-issues#22]
We have the plugin running on our live DC Stash instance. However it does seem to work correctly on our test instance, which is also two nodes. We're currently running Stash v3.11.1

The log error looks something like this:
Any ideas?..

fice-content-manager/tcl/group.tcl HTTP/1.1" com.atlassian.stash.scm.BaseCommand Executed /usr/local/bin/git clone --no-checkout --shared -b 3d74b54ef73d83d9176c6119e30abba439f486df /opt/atlassian/application-data/stash/shared/data/repositories/2935 /opt/atlassian/application-data/stash/tmp/git/backoffice-content-manager-work7570301484005186137.git
2015-08-21 11:30:13,191 ERROR [http-nio-7990-exec-6] *1WNRG90x690x10253x0 2lt1kp 10.194.0.101,10.194.0.111 "POST /mvc/error500 HTTP/1.1" c.a.s.i.web.ErrorPageController There was an unhandled exception loading [/plugins/servlet/edit/projects/COR/repos/backoffice-content-manager/tcl/group.tcl]
com.atlassian.stash.exception.CommandFailedException: '/usr/local/bin/git clone --no-checkout --shared -b 3d74b54ef73d83d9176c6119e30abba439f486df /opt/atlassian/application-data/stash/shared/data/repositories/2935 /opt/atlassian/application-data/stash/tmp/git/backoffice-content-manager-work7570301484005186137.git' exited with code 128 saying: Cloning into '/opt/atlassian/application-data/stash/tmp/git/backoffice-content-manager-work7570301484005186137.git'...
fatal: Remote branch 3d74b54ef73d83d9176c6119e30abba439f486df not found in upstream origin
fatal: The remote end hung up unexpectedly
at com.atlassian.stash.scm.DefaultCommandExitHandler.onError(DefaultCommandExitHandler.java:47) ~[stash-spi-3.11.1.jar:na]
at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.evaluateThrowable(GitCommandExitHandler.java:105) ~[na:na]
at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:159) ~[na:na]
at com.atlassian.stash.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:33) ~[stash-spi-3.11.1.jar:na]
at com.atlassian.stash.scm.BaseCommand.callExitHandler(BaseCommand.java:138) ~[stash-spi-3.11.1.jar:na]
at com.atlassian.stash.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:251) ~[stash-spi-3.11.1.jar:na]
at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:220) ~[stash-spi-3.11.1.jar:na]
at com.atlassian.stash.scm.BaseCommand.call(BaseCommand.java:75) ~[stash-spi-3.11.1.jar:na]
at com.mohamicorp.stash.plugin.editor.PathAtCommit.configureAndCall(PathAtCommit.java:81) ~[na:na]
at com.mohamicorp.stash.plugin.editor.io.ShinyGitPorcelain.clone(ShinyGitPorcelain.java:194) ~[na:na]
at com.mohamicorp.stash.plugin.editor.io.ShinyGitPorcelain.workTree(ShinyGitPorcelain.java:97) ~[na:na]
at com.mohamicorp.stash.plugin.editor.EditorServlet.doPost(EditorServlet.java:294) ~[na:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) ~[na:na]
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181) ~[sitemesh-2.5-atlassian-11.jar:na]
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85) ~[sitemesh-2.5-atlassian-11.jar:na]
at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) ~[StashAuthenticationFilter.class:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) ~[atlassian-trusted-apps-core-4.0.0.jar:na]
at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) ~[na:na]
at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) ~[na:na]
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) ~[na:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) ~[stash-service-impl-3.11.1.jar:na]
at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[ConfigurableWebFilter.class:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_51]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_51]
... 186 frames trimmed
Caused by: com.atlassian.utils.process.ProcessException: Non-zero exit code: 128
at com.atlassian.stash.scm.SummarizingProcessHandler.complete(SummarizingProcessHandler.java:49) ~[stash-spi-3.11.1.jar:na]
at com.atlassian.utils.process.ExternalProcessImpl.wrapUpProcess(ExternalProcessImpl.java:665) ~[atlassian-processutils-1.7.2.jar:na]
at com.atlassian.utils.process.ExternalProcessImpl.finish(ExternalProcessImpl.java:161) ~[atlassian-processutils-1.7.2.jar:na]
at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:218) ~[stash-spi-3.11.1.jar:na]
... 22 common frames omitted

**Comment by mdavoodi** [comment]
I can't seem to reproduce this. Could you turn debugging on in Stash and do this again and post the log? Also what version of Editor for Stash are you using?

**Comment by gadg3ts** [comment]
Debug is already on. Is it possible to send you the logs without them being public?..

**Comment by mdavoodi** [comment]
Yes, send an email to support with the log.

**Comment by mdavoodi** [comment]
Hey gadg3ts, I think we tracked down the error. Theres a workflow bug in which Stash does not stay consistent in the way it creates URL's to the source view for files. If you view the source of the file through the Pull Request View (i.e. clicking the source button), it uses the commit hash instead of the branch name to construct the URL.

We've released a version of Editor for Stash that accounts for this. Try out version 1.5.1 and see if it works for you. You can find it [here](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.plugin.editor-for-stash/versions).

**Comment by gadg3ts** [comment]
I've sent you our logs via email.
I've updated the plugin to 1.5.1 but no longer see the edit button on the same link.
The error message then was in the JS console: "Uncaught ReferenceError: EditorForStash is not defined"

Thanks :)

**Comment by mdavoodi** [comment]
Hey gadg3ts, we've released build 1.5.2. Could you see if you're still seeing the same error? If not I'll close the issue.

**Comment by mdavoodi** [comment]
Closing.
