### ISSUE TITLE
500 error when clicking edit for some files

### ISSUE THREAD

**Issue by Cycododge** [mohamicorp/editor-for-stash-issues#25]
Gives a 500 error on some files when clicking the edit button from a pull requests diff view. The files that it does give the error on is consistent. File length, folder structure, and branch do not seem to make a difference.

Stash v3.11.2

**Comment by mdavoodi** [comment]
Could you post a file it gives an error on? Could you also post the stash log?

**Comment by Cycododge** [comment]
Unfortunately I'm unable to get access to the log.

Here's a file that breaks the editor. ( https://github.com/Cycododge/bad-file-for-stash-editor/blob/master/Defect1653ShowLoad.java ).

Here's the testing I've done:
- Removed partial text: fails
- Removed all text: fails
- Added to filename: fails
- Rename partial: fails
- Remove numbers from file name: passes
- Rename completely: fails
- Duplicate file: passes

**Comment by mdavoodi** [comment]
I can't reproduce this error. Are you saying that you believe that the numbers in the name is causing the error?

**Comment by Cycododge** [comment]
I would say that, but then again it still fails when the entire file is renamed. Either way, I was able to get the localhost log from the server admin. Here are some related traces for you.

That was way too long. Moved the stack track to this readme ( https://github.com/Cycododge/bad-file-for-stash-editor/blob/master/README.md )

**Comment by mdavoodi** [comment]
141 is a kernel level exit code. It looks like git on the machine is failing with a SIGPIPE when running git ls-tree. Could you figure out the version of git running on the stash server? The version of Stash would be useful as well.

**Comment by Cycododge** [comment]
Git v1.8.5.5
Stash v3.11.2

**Comment by mdavoodi** [comment]
I think we've isolated the problem. Could you ask the administrator to update git to a newer version like 2.2? Also is this a windows or linux server?

**Comment by mdavoodi** [comment]
It seems like this is a problem with git and the file system. It's happening when we try and resolve the file mode for the file that's being edited. It looks like newer versions of git handle this a lot better. In the interim we're going to have the file mode default to 10644 if git can't resolve it.

**Comment by Cycododge** [comment]
It's running on linux. I've asked the admin to update, and I will be sure to update you once it's complete. Thank you for your help and time on this issue.

**Comment by ziembam** [comment]
Don't know if this will help you or not, but here is the exception getting thrown by Stash when we're seeing the 500 errors, we pulled it out of the localhost file.

23-Sep-2015 11:17:30.588 SEVERE [http-nio-7990-exec-1996] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [plugins] in context with path [] threw exception
 com.atlassian.stash.exception.CommandFailedException: '/usr/bin/git ls-tree 95a07958c602258d97c51843e4c812a41e9d694b:prod-u01/scripts' exited with code 141

git version:1.8.2.1
stash version: 3.5.1
editor version: 1.4.1

**Comment by mdavoodi** [comment]
This is the same error mentioned here. Try updating git and see if that resolves it. 

We are also releasing a version that gets past this error by defaulting to 10644. as the file mode, but that can cause issues if the file you're editing has executable permissions.

**Comment by Cycododge** [comment]
The git version has been updated to 2.5.0, restarted, and the issue still occurs. Here's the stack trace. I think your fallback solution may be sufficient for our needs. Thank you.

```
25-Sep-2015 02:12:53.137 SEVERE [http-nio-9002-exec-5] org.apache.catalina.core.ApplicationContext.log Unhandled exception occurred whilst decorating page
com.atlassian.stash.exception.CommandFailedException: '/usr/bin/git ls-tree 2af809cc0226488eede91cdc8fda56dd4f745558:src/test/java/com/ ... /selenium/src/test/java/com/ ... /selenium/test/defect' exited with code 141
        at com.atlassian.stash.scm.DefaultCommandExitHandler.onError(DefaultCommandExitHandler.java:43)
        at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.evaluateThrowable(GitCommandExitHandler.java:105)
        at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:159)
        at com.atlassian.stash.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:33)
        at com.atlassian.stash.scm.BaseCommand.callExitHandler(BaseCommand.java:138)
        at com.atlassian.stash.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:251)
        at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:220)
        at com.atlassian.stash.scm.BaseCommand.call(BaseCommand.java:75)
        at com.mohamicorp.stash.plugin.editor.EditorServlet.resolveFileMode(EditorServlet.java:197)
        at com.mohamicorp.stash.plugin.editor.EditorServlet.doGet(EditorServlet.java:180)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at com.atlassian.plugin.servlet.DelegatingPluginServlet.service(DelegatingPluginServlet.java:42)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at com.atlassian.plugin.servlet.ServletModuleContainerServlet.service(ServletModuleContainerServlet.java:52)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.atlassian.stash.internal.web.filters.StandardResponseHeadersFilter.doFilterInternal(StandardResponseHeadersFilter.java:65)
```

**Comment by mdavoodi** [comment]
We've released the 1.52 update that deals with this. Check it out and let me know if it resolves it for you.

**Comment by Cycododge** [comment]
Confirmed! Thank you for your support on this, it is much appreciated.

**Comment by mdavoodi** [comment]
No problem. We would also appreciate it if you could edit your marketplace review to mention that we solved the problem.

**Comment by Cycododge** [comment]
Of course! It is now updated.
