### ISSUE TITLE
Unable to commit edited files

### ISSUE THREAD

**Issue by soloji** [mohamicorp/editor-for-stash-issues#27]
Hello,

I am running bitbucket 4.1.3 on windows 2012 R2. The server does not have internet connections when I try to commit some code I get a 500 error. Checking the logs this the error message:

2015-12-04 14:24:20,341 ERROR [http-nio-8443-exec-1] @G0KEG4x864x83x0 14kv3j9 172.29.34.21 "POST /mvc/error500 HTTP/1.1" c.a.s.i.web.ErrorPageController There was an unhandled exception loading [/plugins/servlet/edit/projects/IAAS/repos/vro_validation/lo.txt]
java.lang.IllegalArgumentException: null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-18.0.jar:na]
at com.atlassian.bitbucket.scm.AbstractCommandBuilder.notBlank(AbstractCommandBuilder.java:433) ~[bitbucket-spi-4.1.3.jar:na]
at com.atlassian.bitbucket.scm.AbstractCommandBuilder.environment(AbstractCommandBuilder.java:300) ~[bitbucket-spi-4.1.3.jar:na]
at com.atlassian.bitbucket.scm.AbstractCommandBuilder.environment(AbstractCommandBuilder.java:22) ~[bitbucket-spi-4.1.3.jar:na]
at com.atlassian.stash.internal.scm.git.command.AbstractGitCommandBuilder.environment(AbstractGitCommandBuilder.java:131) ~[na:na]
at com.atlassian.stash.internal.scm.git.command.AbstractGitCommandBuilder.author(AbstractGitCommandBuilder.java:40) ~[na:na]
at com.atlassian.stash.internal.scm.git.command.AbstractGitCommandBuilder.author(AbstractGitCommandBuilder.java:65) ~[na:na]
at com.mohamicorp.stash.plugin.editor.io.ShinyGitPorcelain.commit(ShinyGitPorcelain.java:266) ~[na:na]
at com.mohamicorp.stash.plugin.editor.io.ShinyGitPorcelain.commitChanges(ShinyGitPorcelain.java:118) ~[na:na]
at com.mohamicorp.stash.plugin.editor.EditorServlet.doPost(EditorServlet.java:335) ~[na:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) ~[na:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) ~[na:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) ~[na:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) ~[na:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) ~[na:na]
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181) ~[sitemesh-2.5-atlassian-11.jar:na]
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85) ~[sitemesh-2.5-atlassian-11.jar:na]
at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) ~[StashAuthenticationFilter.class:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) ~[atlassian-trusted-apps-core-4.2.0.jar:na]
at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) ~[na:na]
at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) ~[na:na]
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) ~[na:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) ~[BeforeLoginPluginAuthenticationFilter.class:na]
at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) ~[bitbucket-service-impl-4.1.3.jar:na]
at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[ConfigurableWebFilter.class:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_60]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_60]
... 200 frames trimmed

**Comment by mdavoodi** [comment]
I believe this has been fixes as of version 2.3.2.
